### ISSUE TITLE
serverless offline not serving other methods than GET

### ISSUE THREAD

**Issue by TurhanOz** [cyberworkz/serverless-templates#8]
#### Description
serving locally the lambda (with `sls offline`) only works for GET methods.
Other methods such as POST are not served, even if they are mapped

#### Screenshots
<img width="752" alt="Capture d’écran 2022-03-29 à 18 32 02" src="https://user-images.githubusercontent.com/3942762/160661199-427bc855-81ad-4ef4-8303-0812d530741f.png">

#### To Reproduce

#1 update app.controller.ts as follow
```import { Controller, Get, Post } from '@nestjs/common';
import { AppService } from './app.service';

@Controller('hello')
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Post()
  postHello():String {
    return this.appService.postHello();
  }
}
```

#2 update app.service.ts as follow
```import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'GET Hello World!';
  }

  postHello():string {
    return 'POST Hello World';
  }
}
```

#3 build the app and launch serverless
$ npm run build
$ npm run start

**Comment by cyberworkz** [comment]
Hi TurhanOZ, 

Thanks for your comment. Two suggestions. You will need to give a response object back. If you alter the code like this it would probably work:
```
@Post()
  postHello(@Res() res: any) {
    return res.status(HttpStatus.CREATED).json({message: 'POST Hello World'});
  }
```
Also, make sure your node version is on 14.19.1 or lower. A higher version can give the problems you describe. See https://github.com/dherault/serverless-offline/issues/1150 for more info
